CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, password_hash text NOT NULL, password_salt text NOT NULL, created_at timestamptz NOT NULL, avatar_url text, cover_url text);
CREATE TABLE IF NOT EXISTS sessions (token text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS combos (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, data jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE INDEX IF NOT EXISTS combos_user_updated_idx ON combos(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS combos_public_idx ON combos(created_at DESC) WHERE data->>'status' = 'Published' AND data->>'visibility' = 'Public';
CREATE INDEX IF NOT EXISTS combos_user_active_updated_idx ON combos(user_id, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS combos_public_active_idx ON combos(created_at DESC) WHERE deleted_at IS NULL AND data->>'status' = 'Published' AND data->>'visibility' = 'Public';
CREATE TABLE IF NOT EXISTS likes (user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, combo_id text NOT NULL REFERENCES combos(id) ON DELETE CASCADE, created_at timestamptz NOT NULL, PRIMARY KEY (user_id, combo_id));
CREATE INDEX IF NOT EXISTS likes_combo_id_idx ON likes(combo_id);
CREATE TABLE IF NOT EXISTS follows (follower_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, followed_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL, PRIMARY KEY (follower_id, followed_id), CHECK (follower_id <> followed_id));
CREATE INDEX IF NOT EXISTS follows_followed_id_idx ON follows(followed_id);
CREATE TABLE IF NOT EXISTS notifications (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_id text REFERENCES users(id) ON DELETE SET NULL, combo_id text REFERENCES combos(id) ON DELETE CASCADE, type text NOT NULL, data jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL, read_at timestamptz);
CREATE INDEX IF NOT EXISTS notifications_user_created_idx ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_user_unread_idx ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;
CREATE TABLE IF NOT EXISTS rate_limits (key text PRIMARY KEY, count integer NOT NULL, reset_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS rate_limits_reset_at_idx ON rate_limits(reset_at);
